image_width: 2056
image_height: 1542
camera_name: ids_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [1461.57941,    0.     , 1028.16795,
            0.     , 1461.83192,  820.47617,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.036581, 0.063865, 0.000594, -0.000878, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1476.23096,    0.     , 1025.56845,    0.     ,
            0.     , 1475.85815,  819.54816,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
